version: '3.5'
services:
  router:
    image: traefik
    container_name: router
    command: [--api, --docker, --configFile=/traefik.toml, 'touch acme.json && chmod 600 acme.json']
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/traefik.toml:/traefik.toml
      - $PWD/acme.json:/acme.json
    networks:
      - backend

  graph:
    build: ./graph
    container_name: graph
    command: ["./scripts/wait-for-it.sh", "prisma:4466", "--", "./scripts/bootstrap.sh"]
    ports:
      - "4000:4000"
    depends_on:
      - prisma
    restart: always
    networks:
      - backend
    labels:
      - "traefik.docker.network=backend"
      - "traefik.enable=true"
      - "traefik.secured.frontend.rule=Host:graph.greedy-amigo.com/graphql"
      - "traefik.secured.protocol=https"
      - "traefik.secured.port=4000"
    environment:
      NODE_ENV:

  prisma:
    image: prismagraphql/prisma:1.24
    container_name: prisma
    restart: always
    ports:
      - "4466:4466"
    depends_on:
      - postgres
    networks:
      - backend
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
            migrations: true

  postgres:
    image: postgres:10.5
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  postgres:

networks:
  backend: