version: '3'
services:
  graph:
    build: ./graph
    container_name: graph
    ports:
      - "80:4000"
    restart: always
    environment:
      NODE_ENV:

  prisma:
    image: prismagraphql/prisma:1.24
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
            migrations: true

  postgres:
    image: postgres:10.5
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: