version: '3.5'
services:
  graph:
    build: ./graph
    container_name: graph
    command: ["./scripts/wait-for-it.sh", "prisma:4466", "--", "./scripts/bootstrap.sh"]
    ports:
      - "80:4000"
    depends_on:
      - prisma
    restart: always
    networks:
      - backend
    environment:
      NODE_ENV:

  prisma:
    image: prismagraphql/prisma:1.24
    container_name: prisma
    restart: always
    ports:
      - "4466:4466"
    depends_on:
      - postgres
    networks:
      - backend
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
            migrations: true

  postgres:
    image: postgres:10.5
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  postgres:

networks:
  backend: