version: '3'
services:
  graph:
    build: ./graph
    container_name: graph
    ports:
      - "80:4000"
    depends_on:
      - prisma
    restart: always
    environment:
      NODE_ENV:

  prisma:
    image: prismagraphql/prisma:1.24
    container_name: prisma
    restart: always
    ports:
      - "4466:4466"
    depends_on:
      - postgres
    environment:
      PRISMA_CONFIG: |
        port: 4466
        migrations: true
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
            migrations: true

  postgres:
    image: postgres:10.5
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: